version: "3"
services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      aurora-app:
        ipv4_address: 10.5.0.5
    container_name: jenkins
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://10.5.0.5:8080/login"]
      interval: 10s
      timeout: 10s
      retries: 5

  python_webhook:
    build: 
      context: .
      dockerfile: python.Dockerfile
    volumes:
      - /var/python_home:/python_home
    networks:
      - aurora-app
    container_name: python-webhook
    restart: unless-stopped
    depends_on:
      jenkins:
        condition: service_healthy
volumes:
  jenkins_home:
networks:
  aurora-app:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

